path_classifiers:
  test:
    - exclude: /
    - XUnitTester
    - Exam
extraction:
  csharp:
    index:
      solution:
        - GeminiLab.Core2.CommandLineParser.sln
      dotnet:
        version: 3.1.402
