name: CI

on:
  push:
    branches:
      - "master"
      - "dev"
      - "f/*"
      - "hotfix"
      - "hotfix/*"
      - "r/*"
  pull_request:
    branches:
      - "master"
      - "dev"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Develop --no-restore
    - name: Pretest
      run: mkdir coverage
    - name: Test
      run: dotnet test -nologo -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput="../coverage/lcov.info" -p:Exclude="\"[xunit.*]*\"" -p:ExcludeByAttribute="CompilerGeneratedAttribute" -v=m XUnitTester/XUnitTester.csproj
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
